# Generated by Django 3.0.5 on 2020-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='result',
            field=models.CharField(max_length=30),
        ),
    ]
