# Generated by Django 3.0.5 on 2020-06-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Server', '0002_auto_20200504_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Google', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
