# Generated by Django 3.0.5 on 2020-06-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Server', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='answer',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
