# Generated by Django 3.0.5 on 2020-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_auto_20200602_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
