# Generated by Django 3.0.5 on 2020-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_session_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(max_length=300),
        ),
    ]
